### ISSUE TITLE
Password Requirements : CDP

### ISSUE THREAD

**Issue by vsellappa** [cloudera-labs/cloudera-deploy#10]
**CDP Password requirements not checked / enforced upfront.**

Quickstart depends on `cdp cli` for creating a CDP environment and requires a specific password standard . This is not enforced or checked upfront, thereby failing later if an incorrect password is set.

The CDP password requirements must be checked upfront *before* cluster creation.

**Comment by Chaffelson** [comment]
Fixed in #11
