### ISSUE TITLE
Log Levels : 

### ISSUE THREAD

**Issue by vsellappa** [cloudera-labs/cloudera-deploy#13]
**Feature Request**

It would be nice to have different log levels and the logging to be more verbose by default vs whats output when the ansible scripts actually run.
This would make it easier to check if a specific step is executing or has stopped. , especially important when during creation of VM's that take longer to finish.

**Comment by Chaffelson** [comment]
Unfortunately not solved upstream
https://github.com/ansible/ansible/issues/38786

**Comment by wmudge** [comment]
Yes, outside of using the `-v` flag at runtime and the `verbosity` parameter in the `debug` module, we don't have a lot of (easy) options.
