### ISSUE TITLE
aws-latest Image missing an Posgresql update from Devel

### ISSUE THREAD

**Issue by rsuplina** [cloudera-labs/cloudera-deploy#141]
Currenlty if someone runs ansible-navigator to spin  up aws-iaas with `ghcr.io/cloudera-labs/cldr-runner:aws-latest` it will fail at
![Screenshot 2024-05-17 at 14 47 53](https://github.com/cloudera-labs/cloudera-deploy/assets/111508615/9cfbb187-0f3f-490a-87d1-76594973a515)

This happens since PostgreSQL changed to url for the keys.
https://github.com/cloudera-labs/cloudera.cluster/commit/c0b5d85f045bcf3d37f8f94cb5c3c580c47866a3

**Comment by wmudge** [comment]
I believe this has been fixed with the updates to `cldr-runner` in https://github.com/cloudera-labs/cldr-runner/pull/81 and in `cloudera.cluster` in https://github.com/cloudera-labs/cloudera.cluster/pull/188
