### ISSUE TITLE
SSH_AUTH_SOCK across OS : 

### ISSUE THREAD

**Issue by vsellappa** [cloudera-labs/cloudera-deploy#17]
**Make the SSH_AUTH_SOCK implementation O.S agnostic**

The current implementation of SSH_AUTH_SOCK is O.S specific specifically OSX specific.  
The below hard-codes the target path that works only for OSX. 

`--mount type=bind,src=$SSH_AUTH_SOCK,target=/run/host-services/ssh-auth.sock \`

Change this to make it work for all OS's ,  specifically Linux.

**Comment by AlexHff** [comment]
Is there a quick fix for this issue?

**Comment by vsellappa** [comment]
@AlexHff Yes. There is a fix in today

**Comment by vsellappa** [comment]
@AlexHff If you are in a rush , check #24 .

**Comment by AlexHff** [comment]
@vsellappa Thanks!

**Comment by wmudge** [comment]
PR committed
