### ISSUE TITLE
SSH_AUTH_SOCK not set on Windows

### ISSUE THREAD

**Issue by fletchjeff** [cloudera-labs/cloudera-deploy#34]
When running the `quickstart.sh` script on an Ubuntu WSL session on Windows, the `SSH_AUTH_SOCK` variable isn't set as the `ssh-agent` isn't started by default.

```
$ ./quickstart.sh
Checking if Docker is running...
Docker OK
full-latest: Pulling from cloudera-labs/cldr-runner
Digest: sha256:15442500076f42918fd82f5f94cf0aaf4564aa235bd66b47edb2ec052e099e59
Status: Image is up to date for ghcr.io/cloudera-labs/cldr-runner:full-latest
ghcr.io/cloudera-labs/cldr-runner:full-latest
Ensuring default credential paths are available in calling using profile for mounting to execution environment
Ensure Default profile is present
Custom Cloudera Collection path not found
Mounting /mnt/c/Users/jeff/tmp to container as Project Directory /runner/project
Creating Container cloudera-deploy from image ghcr.io/cloudera-labs/cldr-runner:full-latest
Checking OS
SSH_AUTH_SOCK is empty or not set, unable to proceed. Exiting
```

One possible fix would be to add a line to the script to check and start the `ssh-agent`. But running `ssh-agent` directly doesn't set the `SSH_AUTH_SOCK` variable as it needs to be wrapped in an `eval`.

Would it be possible to add something like the following to the `quickstart.sh` script?
```
if pgrep -x "ssh-agent" >/dev/null
then
    echo "ssh-agent is running"
else
    echo "ssh-agent stopped"
    eval `ssh-agent -s` 
fi
```

I tried adding it to the start of the `quickstart.sh` script and it worked fine.

**Comment by wmudge** [comment]
To be consistent with how we handle Docker, we should check and error with a clear message, e.g. https://github.com/cloudera-labs/cloudera-deploy/blob/main/quickstart.sh#L33-L34

**Comment by wmudge** [comment]
Updated in https://github.com/cloudera-labs/cloudera-deploy/pull/36
