### ISSUE TITLE
tag "full_cluster" missing on task "Install Cloudera Manager agents"

### ISSUE THREAD

**Issue by okleber** [cloudera-labs/cloudera-deploy#40]
the task "Install Cloudera Manager agents" located on cluster.yml is missing the tag "full_cluster". Not sure if this was made intentionally or not, but as I get used to use the tag "full_cluster" to deploy on premisse, now my scripts are failing.

**Comment by Chaffelson** [comment]
Now fixed in devel, will be in next release.
