### ISSUE TITLE
"unknown flag: --mount" in quickstart.sh

### ISSUE THREAD

**Issue by olegv-cldr** [cloudera-labs/cloudera-deploy#58]
As the pre-req to run `cloudera-deploy`, I have installed the default docker version on CentOS 7.9 as follows:
`yum install docker`

That's the version that was installed:
```
# docker --version
Docker version 1.13.1, build 7d71120/1.13.1
```

Now, while trying to run `quickstart.sh` - I got the following error:

```
./quickstart.sh
Checking if Docker is running...
Docker OK
Trying to pull repository ghcr.io/cloudera-labs/cldr-runner ...
full-latest: Pulling from ghcr.io/cloudera-labs/cldr-runner
Digest: sha256:01504a335c7fe1c29ba695ca996b464be28925a545f7f2b5bb1c1624e145e208
Status: Image is up to date for ghcr.io/cloudera-labs/cldr-runner:full-latest
Ensuring default credential paths are available in calling using profile for mounting to execution environment
Ensure Default profile is present
Custom Cloudera Collection path not found
Mounting /home/ansible to container as Project Directory /runner/project
Creating Container cloudera-deploy from image ghcr.io/cloudera-labs/cldr-runner:full-latest
Checking OS
SSH authentication for container taken from /tmp/ssh-bAkDNAJcUgfV/agent.9389
Creating new execution container named 'cloudera-deploy'
unknown flag: --mount
See 'docker run --help'.
```

The above version does not recognise "**--mount**" flag. 
It looks like "--mount" was introduced only in Docker 17.05
https://docs.docker.com/engine/release-notes/17.05/#client

**Comment by olegv-cldr** [comment]
It seems that the correct approach is to install 
`yum install docker-ce`

Once completed, docker version looks better:
```
# docker --version
Docker version 20.10.8, build 3967b7d
```

**Comment by Chaffelson** [comment]
Right, maybe we could update the readme to be more explicit on the right version for Linux install.
https://github.com/cloudera-labs/cloudera-deploy/blob/main/readme.adoc#211-install-docker
