### ISSUE TITLE
what's the password of kerberos users?

### ISSUE THREAD

**Issue by cftang** [cloudera-labs/cloudera-deploy#69]
it's a great tool,
but where can I find the password of kerberos users if kerberos=true in definition.yml?
thanks in advance

**Comment by WillDyson** [comment]
Hi @cftang, thanks for your question. When Cloudera Manager generates a new principal, it will randomly generate a password to assign as the principal's password. This password is never used for authentication and it is not retained. Instead, the keytab files generated are used for authentication.

**Comment by cftang** [comment]
Thanks  I get it.
