### ISSUE TITLE
Can't detect the required Python library cryptography (>= 1.2.3)

### ISSUE THREAD

**Issue by olegv-cldr** [cloudera-labs/cloudera-deploy#75]
While testing the deployment in the internal (cloudcat) and external environment - ran into the following issue:

`TASK [cloudera.cluster.ca_server : Generate root private key] ****************************************************************************************
Friday 28 January 2022  00:32:45 +0000 (0:00:00.854)       0:08:16.774 ********
fatal: [cla-tt-2a-mas1.clatest.telstraglobal.net]: FAILED! => {"changed": false, "msg": "Can't detect the required Python library cryptography (>= 1.2.3)"}
`

Check inside of the Docker:
```
cldr full-v1.5.3 #> pip show cryptography
Name: cryptography
Version: 3.3.2
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: https://github.com/pyca/cryptography
Author: The cryptography developers
Author-email: cryptography-dev@python.org
License: BSD or Apache License, Version 2.0
Location: /usr/local/lib64/python3.8/site-packages
Requires: cffi, six
Required-by: adal, ansible-base, azure-cli-core, azure-identity, azure-keyvault, azure-storage, msal, openstacksdk, paramiko, pyOpenSSL, pypsrp, pyspnego, requests-credssp, requests-ntlm
```

**Comment by olegv-cldr** [comment]
To capture an internal discussion on this issue, it looks like the following change might be required:
For roles/prereqs/os/tasks/main-RedHat.yml:
`- name: Setup System python on Rhel8
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8
  block:
    - name: Check if Python3 is installed
      shell: python3 --version
      register: __py3_check
      changed_when: false
      ignore_errors: true

    - name: install python3 if necessary
      when: __py3_check.rc != 0
      ansible.builtin.package:
        lock_timeout: 180
        name: python3
        update_cache: yes
        state: present

    - name: Check if Python2 is installed
      shell: python2 --version
      register: __py2_check
      changed_when: false
      ignore_errors: true

    - name: install python2 if necessary
      when: __py2_check.rc != 0
      ansible.builtin.package:
        lock_timeout: 180
        name: python2
        update_cache: yes
        state: present

    - name: Ensure Python symlink available for Cloudera Manager and Ranger
      ansible.builtin.raw: |
        if [ -f /usr/bin/python2 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python2 /usr/bin/python;
        fi
`

**Comment by olegv-cldr** [comment]
also, for this to work properly you need to tell Ansible not to use the legacy python discovery process in your inventory:

```
[all:vars]
ansible_python_interpreter=auto
```

**Comment by HirossxD** [comment]
Will this work on rhel7 as well ?

**Comment by HirossxD** [comment]
Had same issue on rhel7. problem was old pip2 version. upgrading from pip 8 to pip 20 solved issue.
